namespace SpriteKind {
    export const background = SpriteKind.create()
    export const desert = SpriteKind.create()
    export const obstacle = SpriteKind.create()
}
scene.onHitWall(SpriteKind.Player, function (sprite, location) {
    jumpcount = 0
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (jumpcount < 1) {
        knight.vy = -100
        jumpcount += 2
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.obstacle, function (sprite, otherSprite) {
    game.over(false)
})
function createCloud () {
    let clouds: Image[] = []
    cloud = sprites.createProjectileFromSide(clouds[randint(0, clouds.length - 1)], -30, 0)
    cloud.bottom = randint(30, 55)
    cloud.z = -2
}
function setupFrames () {
    doveFrames = [
    img`
        . . . . . . . . . . . . 
        . . . . . 1 1 1 1 . . . 
        . . . . 1 1 1 1 . . . . 
        . . . . 1 1 1 . . . . . 
        . . . . 1 1 1 . . . . . 
        . . . . 1 1 1 . . . . . 
        . . 1 1 1 1 1 1 . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        `,
    img`
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . 1 1 1 1 1 1 . . 
        . . . 1 1 1 1 1 . . . . 
        . . . 1 1 1 1 . . . . . 
        . . 1 1 1 1 1 1 . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        `,
    img`
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . 1 1 1 1 . . . . . 
        . . 1 1 1 1 1 1 . . . . 
        . . . 1 1 1 1 1 1 1 1 . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        `,
    img`
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . 1 1 1 1 1 1 . . . . 
        . . . 1 1 1 1 . . . . . 
        . . . 1 1 1 1 1 1 . . . 
        . . . . 1 1 1 1 1 1 1 . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        `,
    img`
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . 1 1 1 1 1 1 . . . . 
        . . . 1 1 1 1 . . . . . 
        . . . 1 1 1 1 . . . . . 
        . . . . 1 1 1 1 1 . . . 
        . . . . . 1 1 1 1 1 . . 
        . . . . . . . . . . . . 
        `,
    img`
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . 1 1 1 1 1 1 . . . . 
        . . . 1 1 1 1 . . . . . 
        . . . 1 1 1 1 . . . . . 
        . . . . 1 1 1 1 1 . . . 
        . . . . . 1 1 1 1 1 . . 
        . . . . . . . . . . . . 
        `,
    img`
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . 1 1 1 1 1 1 . . . . 
        . . . 1 1 1 1 . . . . . 
        . . . 1 1 1 1 1 1 . . . 
        . . . . 1 1 1 1 1 1 1 . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        `,
    img`
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . 1 1 1 1 . . . . . 
        . . 1 1 1 1 1 1 . . . . 
        . . . 1 1 1 1 1 1 1 1 . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        `,
    img`
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . 1 1 1 1 1 1 . . 
        . . . 1 1 1 1 1 . . . . 
        . . . 1 1 1 1 . . . . . 
        . . 1 1 1 1 1 1 . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        `,
    img`
        . . . . . . . . . . . . 
        . . . . . 1 1 1 1 . . . 
        . . . . 1 1 1 1 . . . . 
        . . . . 1 1 1 . . . . . 
        . . . . 1 1 1 . . . . . 
        . . . . 1 1 1 . . . . . 
        . . 1 1 1 1 1 1 . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        . . . . . . . . . . . . 
        `
    ]
    animation.runImageAnimation(
    dove,
    doveFrames,
    40,
    true
    )
    knightFrames = [
    img`
        ................
        ................
        .....ffffff.....
        ...fffffffff....
        ..fffffffffff...
        ..ffffffccccf...
        ..ffffcccccccf..
        ..fccccffffccf..
        .fffffffcccfff..
        .ffcbbcbfbbccf..
        .fccbdb1fddcf...
        ..fcccbddddf....
        ...ffccbbbcf....
        ....bddcbbcf....
        ....bddccaaf....
        ....fccfbbbf....
        .....ffffff.....
        ......ffff......
        ......f..f......
        ................
        ................
        `,
    img`
        ................
        ................
        .....ffffff.....
        ...fffffffff....
        ..fffffffffff...
        ..ffffffccccf...
        ..ffffcccccccf..
        ..fccccffffccf..
        .fffffffcccfff..
        .ffcbbcbfbbccf..
        .fccbdb1fddcf...
        ..fcccbddddf....
        ...ffccbbbcf....
        ....bddcbbcfb...
        ....bddccaafb...
        .....fccbbbf....
        .....ffffff.....
        ......ffff......
        ......f..f......
        .........f......
        ................
        `,
    img`
        ................
        ................
        .....ffffff.....
        ...fffffffff....
        ..fffffffffff...
        ..ffffffccccf...
        ..ffffcccccccf..
        ..fccccffffccf..
        .fffffffcccfff..
        .ffcbbcbfbbccf..
        .fccbdb1fddcf...
        ..fcccbddddf....
        ...ffccbbbcf....
        ...bdddcbbcfdb..
        ...bdddccaafdb..
        ....fccfbbbf....
        .....ffffff.....
        ......ffff......
        .......ff.......
        ........f.......
        ................
        `,
    img`
        ................
        ................
        .....ffffff.....
        ...fffffffff....
        ..fffffffffff...
        ..ffffffccccf...
        ..ffffcccccccf..
        ..fccccffffccf..
        .fffffffcccfff..
        .ffcbbcbfbbccf..
        .fccbdb1fddcf...
        ..fcccbddddf....
        ...ffccbbbcf....
        ...bdddcbbcfdb..
        ...bdddccaafdb..
        ....fccfbbbf....
        .....ffffff.....
        ......ffff......
        .......ff.......
        .......f........
        ................
        `,
    img`
        ................
        ................
        .....ffffff.....
        ...fffffffff....
        ..fffffffffff...
        ..ffffffccccf...
        ..ffffcccccccf..
        ..fccccffffccf..
        .fffffffcccfff..
        .ffcbbcbfbbccf..
        .fccbdb1fddcf...
        ..fcccbddddf....
        ...ffccbbbcf....
        ...bdddcbbcfdb..
        ...bdddccaafdb..
        ....fccfbbbf....
        .....ffffff.....
        ......ffff......
        ......f..f......
        ......f.........
        ................
        `,
    img`
        ................
        ................
        .....ffffff.....
        ...fffffffff....
        ..fffffffffff...
        ..ffffffccccf...
        ..ffffcccccccf..
        ..fccccffffccf..
        .fffffffcccfff..
        .ffcbbcbfbbccf..
        .fccbdb1fddcf...
        ..fcccbddddf....
        ...ffccbbbcf....
        ...bdddcbbcfdb..
        ...bdddccaafdb..
        ....fccfbbbf....
        .....ffffff.....
        ......ffff......
        ......f..f......
        ................
        ................
        `
    ]
    obstacles = [
    img`
        ......................
        ..........7...........
        ..........77..........
        .........677..........
        ........66777.........
        ........66777.........
        ........677777........
        .......6677777........
        ......66677777........
        ........66666.........
        ........6766..........
        .......6667777........
        ......666777777.......
        ......6677777777......
        ......67777777777.....
        ..66666777777777777...
        ...666667777766666....
        ........666777........
        ........667777........
        ......667777777.......
        ...66677777777777.....
        .66677777777777777....
        6667777777777777777776
        ...666667777777777776.
        .....6666777777777666.
        .......66eeee.........
        .........feef.........
        .........feef.........
        ......6..feef...6.....
        ...6....feefef.6......
        ..666...fefeef........
        ......................
        `,
    img`
        ...................................
        ..........7........................
        ..........77.......................
        .........677.......................
        ........66777......................
        ........66777......................
        ........677777.....................
        .......6677777.....................
        ......66677777.....................
        ........66666......................
        ........6766.......................
        .......6667777.....................
        ......666777777....................
        ......6677777777...................
        ......67777777777..................
        ..66666777777777777................
        ...666667777766666.................
        ........666777.....................
        ........667777.....................
        ......667777777....................
        ...66677777777777..................
        .66677777777777777.................
        6667777777777777777776.............
        ...666667777777777776....bbb.......
        .....6666777777777666..cc313cc.....
        .......66eeee.........c331331bc....
        .........feef.........c3b333b3c....
        .........feef..........cbbbbbc.....
        ......6..feef...6.......ccccc......
        ...6....feefef.6.........b1b..b....
        ..666...fefeef..........bd1b...b...
        ...................................
        `,
    img`
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............................
        ..............bbbbb...........
        ............bbddddbb..........
        ...........bdddddddc..........
        ..........cddddddddc..........
        .........cbdddddddbcc.........
        .........cbbddddbcccc.........
        ........ccdbbbccccccc.........
        ........cccddddccdddcc........
        .......cdbccbbccdddddc........
        .......cbddbbbccdddddc........
        .......ccbbbbcbcbdddbc........
        ......cbbcccccbbbbbccc........
        ......ccbbcccccdddddbc........
        ......ccccccbbbbbccccc....b...
        ......cccccccbbbbbcccc..c.....
        ...b..ccccccccbbbbbccc...b....
        ..............................
        ..............................
        `,
    img`
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ...................................
        ..............bbbbbb...............
        ............bbddddddbb.............
        ...........bbddbbbbddbb............
        ..........edbdbddddbdbde...........
        ..........edbddbbbbddbde...........
        ..........fbdbbddddbbdbe...........
        ..........fedddbbbbdddee...........
        ..........feebddddddbeef...........
        ..........ffeeeeeeeeeeef...........
        ..........ffeeefeeeeeeef...........
        ..........ffefeeeefeefeef..........
        ..........feefefefefefeee..........
        .........ffeeeefeefeeffee..........
        ....e..e.feeeeffeeeeeeffe..........
        ...e.....eeeefffefeeeefff..........
        .........eeeeefeefeeeeeff..........
        ...................................
        ...................................
        `,
    img`
        ......................
        ..........7...........
        ..........77..........
        .........677..........
        ........66777.........
        ........66777.........
        ........677777........
        ........677777........
        .......6677777........
        ........66666.........
        ........6766..........
        .......6667777........
        ......666777777.......
        ......6677777777......
        ......67777777777.....
        .....66777777777777...
        ....6666777776666.....
        .........66777........
        ........667777........
        ......667777777.......
        ...66677777777777.....
        ..6677777777777777....
        .667777777777777777776
        ....66667777777777776.
        ......66677777777766..
        ........6eeee.........
        .........feef.........
        ....6....feef.........
        ..66.6...feef...6.6...
        ..6.....feefef........
        ..66....fefeef........
        ......................
        `,
    img`
        ................
        ................
        .....ffffff.....
        ...fffffffff....
        ..fffffffffff...
        ..ffffffccccf...
        ..ffffcccccccf..
        ..fccccffffccf..
        .fffffffcccfff..
        .ffcbbcbfbbccf..
        .fccbdb1fddcf...
        ..fcccbddddf....
        ...ffccbbbcf....
        ...bdddcbbcfdb..
        ...bdddccaafdb..
        ....fccfbbbf....
        .....ffffff.....
        ......ffff......
        ......f..f......
        ................
        ................
        `
    ]
}
sprites.onDestroyed(SpriteKind.obstacle, function (sprite) {
    info.changeScoreBy(1)
})
function createTree () {
    let trees: Image[] = []
    tree = sprites.createProjectileFromSide(trees[randint(0, trees.length - 1)], -50, 0)
    tree.bottom = 100
    tree.z = -1
}
let grass: Sprite = null
let projectile: Sprite = null
let obstacleImage: Image = null
let tree: Sprite = null
let obstacles: Image[] = []
let knightFrames: Image[] = []
let doveFrames: Image[] = []
let cloud: Sprite = null
let jumpcount = 0
let dove: Sprite = null
let knight: Sprite = null
knight = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f f f f f f . . . . 
    . . . f f f f f f f f f f . . . 
    . . f f f b b b b b b f f f . . 
    . . f f b f f f f f f b b f . . 
    . . f b f f f f f f f f b f . . 
    . . f f f f b b b b f f f f . . 
    . f f b f 1 f c c f 1 f b f f . 
    . f b b c 1 f d d f 1 c b b f . 
    . . f b b d d d d d d b b f . . 
    . . . f b b c c c c b b f . . . 
    . . f c f f f f f f f f c f . . 
    . . c d f f f f f f f f d c . . 
    . . c d f c c a a c c f d c . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
knight.setStayInScreen(true)
controller.moveSprite(knight)
let statusbar = statusbars.create(25, 3, StatusBarKind.Health)
statusbar.attachToSprite(knight)
statusbar.value = 100
scene.setBackgroundColor(11)
let gravity = 400
knight.ay = gravity
knight.x = 20
dove = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.Projectile)
dove.setPosition(150, 20)
dove.setVelocity(-120, 50)
setupFrames()
game.onUpdate(function () {
    if (knight.bottom > 105) {
        knight.bottom = 105
        knight.vy = 0
        knight.ay = 0
        animation.runImageAnimation(
        knight,
        [img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `],
        50,
        true
        )
    }
})
game.onUpdate(function () {
    if (dove.x < 0) {
        dove.setPosition(randint(160, 240), randint(20, 60))
    }
})
game.onUpdateInterval(2000, function () {
    obstacleImage = obstacles[randint(0, obstacles.length - 1)]
    projectile = sprites.createProjectileFromSide(obstacleImage, -100, 0)
    projectile.bottom = 105
    projectile.setKind(SpriteKind.obstacle)
})
game.onUpdateInterval(1000, function () {
    if (Math.percentChance(40)) {
        createCloud()
    }
})
forever(function () {
    knight.ay = 200
    if (knight.isHittingTile(CollisionDirection.Bottom)) {
        jumpcount = 0
    }
})
forever(function () {
    if (Math.percentChance(60)) {
        createTree()
        if (Math.percentChance(50)) {
            pause(randint(150, 300))
            createTree()
        }
    }
    pause(1500)
})
game.onUpdateInterval(200, function () {
    if (Math.percentChance(40)) {
        let grassImages: Image[] = []
        grass = sprites.createProjectileFromSide(grassImages[randint(0, grassImages.length - 1)], -50, 0)
        grass.bottom = 100
        grass.z = -1
    }
})
